title: "Cards"
description: |
  Cards can be used ot organize sections of image with text.

patterns:
  responsive-cards:
    title: "Responsive Cards"
    description: |
      Responsive cards are a descreate way to seperate items.
  card:
    title: "card"
    description: |
      Card are a simple ways to seperate items.
  column-cards:
    title: "Column Cards"
    description: |
      Column Cards are an easy way to differantiate between multipule items.
  product-card:
    title: "Product Card"
    width: 400
    description: |
      The product card is used on the product listing page to display each available product.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
  cart-card:
    title: "Cart Card"
    height: 10
    description: |
      The product card is used to list the products added on the cart.
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
